2025-06-08 02:39:24,783 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:25,206 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:26,015 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:27,606 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:27,966 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:29,631 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:30,247 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:31,397 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:31,628 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:31,957 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:32,834 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:33,065 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:34,433 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:34,702 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:35,994 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:37,682 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:37,979 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:38,808 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:40,810 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:41,217 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:42,861 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:43,516 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:44,872 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:45,093 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:45,418 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:46,272 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:46,491 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:47,846 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:48,138 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
2025-06-08 02:39:49,266 - ERROR - Exception in parse_track_info
Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 130, in parse_track_info
    track_artist = track_info['album']['artist']
                   ~~~~~~~~~~^^^^^^^^^
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "c:\Users\ali haidari\code\projects\py\skate_dat\scraper.py", line 144, in parse_track_info
    return {'name':track_info[1], 'artist':track_info[0], 'missing':True}
                   ~~~~~~~~~~^^^
KeyError: 1
